package com.dsip.backend.test.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for executing the test workflow.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExecuteWorkflowRequest {

    /**
     * Path to the price data CSV file generated by the first endpoint.
     */
    @NotBlank(message = "CSV file path is required")
    @JsonProperty("csv_file_path")
    private String csvFilePath;

    /**
     * Tracker ID of the already-created DSIP tracker.
     */
    @NotNull(message = "Tracker ID is required")
    @JsonProperty("tracker_id")
    private Integer trackerId;
}
